name: Gif Comment
on: 
  issues: 
    types: [opened]

jobs:
  comment: 
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Funny comments
        uses: Marta83/funny-comment-action@v2.1
        id: FunnyComment
        with:
          GUTHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
          comment_type: 'gif'
